Update the project overview diagram
NordicSemiconductor/asset-tracker-cloud-docs pull request #105
Opened 2021-04-16 15:55 UTC by coderbyheart

The [project overview diagram](https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/blob/f561d88e6835f12074d55418838c29910bbad53c/docs/project/system-overview.jpg) is outdated.

Instead I would like to add an up to date version, that also has links to the respective components. This can be done nicely using Graphviz, with it's SVG export, however including the SVG in the sphinx build needs more investigation: it needs to be embedded as a plain SVG not as an image.

Here is a PDF version of the SVG:
[system-overview.pdf](https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/files/6326378/system-overview.pdf)

2021-04-20 05:17 UTC, peknis commented
Gell Geolocation  -> Cell Geolocation, I think.

2021-04-21 12:25 UTC, peknis requested changes

2021-04-21 12:25 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
I would leave out the mention about the popularity of JavaScript.

2021-04-21 12:25 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
A couple of lines below, "**It** provides... refers to what exactly? The web application, the cloud, the whole system? Always, be careful when saying "it". The reader needs to know where it refers to.

2021-04-21 12:25 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
Avoid passive voice and talk to the reader who is using these instructions. For example: "After the cloud account has been configured, ...". Could you perhaps say "After you have configured the cloud account, it provides..."

2021-04-21 12:46 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
> I would leave out the mention about the popularity of JavaScript.
Why?

2021-04-21 12:49 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
> Avoid passive voice and talk to the reader who is using these instructions. For example: "After the cloud account has been configured, ...". Could you perhaps say "After you have configured the cloud account, it provides..."

That's not appropriate, because it's not the user that configures the cloud account, it's CDK which provides a template to CloudFormation (which is an infrastructure as a service service by AWS) that does the configuration. All the user has to do is to issue a command and sit back and wait.

I especially want to provide tools that do most of the heavy lifting for the user, so they don't have to do much. That's why I think passive voice here is approporiate.

2021-04-21 13:19 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
The popularity of JavaScript is not relevant here.
Right, I did not get what is done by the system and what the user needs to do. Anyway, we need to make this clear to the reader.

2021-04-21 13:34 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
> The popularity of JavaScript is not relevant here.

It is because it's popularity is one of the reasons why TypeScript was chosen as the programming language for the project.

2021-04-22 05:05 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
Do you always need to justify your choice of the programming language? Believe me, this does not belong in technical customer document.

2021-04-22 07:29 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
> Do you always need to justify your choice of the programming language? 

Yes, because it's not a random choice. Especially for cloud development there are widely used alternatives like Java, Python, or Go and therefore it's good to give users the information why JavaScript is used here, because it affects every line of code in the project.

> Believe me, this does not belong in technical customer document.

Why? What harm does it cause to include this?

2021-04-22 09:01 UTC, peknis commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
I understand that you want to justify the language choice in a private project, but in a large international company, you are not explaining why you ended up using a certain language. At least not in technical customer documentation.

2021-04-22 09:09 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
Why not?

2021-04-29 07:58 UTC, umapraseeda commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
I also suggest that we remove this sentence.

2021-04-29 08:38 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
This is not part of the PR.

And, again, why should this be removed? I have asked multiple times for an explanation: **what is so harmful about this explanation that it needs to removed?**

2021-04-29 14:35 UTC, coderbyheart commented on docs/project/SystemOverview.rst
>  JavaScript is the most popular language according to the `2019 Stack Overflow survey <https://insights.stackoverflow.com/survey/2019#technology>`_.
The explanation is that
> it goes against the principles of not adding additional information that gets in the way of the user flow. I also see this content as extraneous information, it really doesn't help the user to know the reason a choice has been made. So, the explanation is not harmful, but from a stylistic point of view, it is not considered good usability. 

I've **moved** the technical details therefore to an ADR.

2021-05-07 12:56 UTC, umapraseeda commented on docs/project/SystemOverview.rst
> +nRF Asset Tracker provides the tools to configure the developer's cloud account for use with the developer's devices and the single-page application (SPA).
```suggestion
The nRF Asset Tracker provides the tools to configure the developer's cloud account for use with the developer's devices and the single-page application (SPA).
```

2021-05-10 06:32 UTC, umapraseeda approved these changes

2021-05-10 06:38 UTC, peknis approved these changes

2021-05-10 07:36 UTC, merged