Update v1.5.x docs with latest changes
NordicSemiconductor/asset-tracker-cloud-docs pull request #139
Opened 2021-05-10 10:23 UTC by coderbyheart

2021-05-10 11:48 UTC, peknis requested changes

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +Login and create the resource group
```suggestion
Log in and create the resource group
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +1. Login to the shell:
```suggestion
1. Log in to the shell:
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +   In this example, we use ``nrfassettrackerci`` as the resource group name.
```suggestion
   In this example, ``nrfassettrackerci`` is used as the resource group name.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +   In this example, we use ``nrfassettrackerci`` as the application name.
```suggestion
   In this example, ``nrfassettrackerci`` is used as the application name.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +   There is an undocumented limit of 2 instances per ADU account, so the CI should be run against a separate Device Update instance.
```suggestion
   There is an undocumented limit of two instances per ADU account, so the CI should be run against a separate Device Update instance.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +   In this example, we use ``nRFAssetTrackerADUCI`` as the resource group and Device Update instance name.
```suggestion
   In this example, ``nRFAssetTrackerADUCI`` is used as the resource group and Device Update instance name.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +   In this example, we use ``northeurope`` as the location name.
```suggestion
   In this example, ``northeurope`` is used as the location name.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +#. For enabling the test-runner to programmatically login users, enable `the resource owner password credentials (ROPC) flow <https://docs.microsoft.com/EN-US/azure/active-directory-b2c/configure-rop
```suggestion
#. For enabling the test-runner to programmatically log in users, enable `the resource owner password credentials (ROPC) flow <https://docs.microsoft.com/EN-US/azure/active-directory-b2c/configure-ropc?tabs=app-reg-ga>`_ with the following settings on the Active Directory B2C:
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/ContinuousIntegration.rst
> +Setup continuous integration on GitHub
```suggestion
Set up continuous integration on GitHub
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/GettingStarted/Deploy.rst
> +   There is a limit of `2 instances per subscription <https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-resources#device-update-instance>`_, so the ADU instance needs to be s
```suggestion
   There is a limit of `two instances per subscription <https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-resources#device-update-instance>`_, so the ADU instance needs to be shared between multiple IoT hubs.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/GettingStarted/Deploy.rst
> +   In this example, we use ``nRFAssetTrackerADU`` as the resource group and Device Update instance name.
```suggestion
   In this example, ``nRFAssetTrackerADU`` is used as the resource group and Device Update instance name.
```

2021-05-10 11:48 UTC, peknis commented on docs/azure/GettingStarted/Deploy.rst
>     In this example, we use ``northeurope`` as the location name.
```suggestion
   In this example, ``northeurope`` is used as the location name.
```

2021-05-10 11:48 UTC, peknis commented on docs/firmware/azure/BuildingUsingDocker.rst
> +Location of the HEX file
This section could be on the same level as the devices -> ====

2021-05-10 11:48 UTC, peknis commented on docs/firmware/azure/BuildingUsingLocalSystem.rst
> +************************
This section could be at the same level as the devices -> ====

2021-05-11 08:31 UTC, umapraseeda commented on docs/azure/ContinuousIntegration.rst
> +   Use a short name (not more than 16 characters) composed of numbers and lower-case letters only.
```suggestion
   Use a short name (not more than 16 characters) composed of numbers and lowercase letters only.
```

2021-05-11 08:31 UTC, umapraseeda commented on docs/azure/ContinuousIntegration.rst
> +   There is an undocumented limit of 2 instances per ADU account, so the CI should be run against a separate Device Update instance.
```suggestion
   There is an undocumented limit of two instances per ADU account, so the CI must be run against a separate Device Update instance.
```

2021-05-12 07:05 UTC, umapraseeda approved these changes

2021-05-25 08:53 UTC, peknis approved these changes

2021-05-25 08:54 UTC, merged