Reword features paragpraph
NordicSemiconductor/asset-tracker-cloud-docs pull request #145
Opened 2021-05-12 12:58 UTC by coderbyheart

#144 was closed accidentially.

2021-05-12 13:06 UTC, peknis requested changes

2021-05-12 13:06 UTC, peknis commented on docs/aws/Index.rst
> +The :file:`.feature` files in the folder are used to continuously verify the reference implementation using :ref:`Continuous Integration <aws-continuous-integration>`.
```suggestion
The :file:`.feature` files in the folder are used to continuously verify the reference implementation using :ref:`aws-continuous-integration`.
```

2021-05-12 13:06 UTC, peknis commented on docs/azure/Index.rst
> +The :file:`.feature` files in the folder are used to continuously verify the reference implementation using :ref:`Continuous Integration <azure-continuous-integration>`.
```suggestion
The :file:`.feature` files in the folder are used to continuously verify the reference implementation using :ref:`azure-continuous-integration`.
```

2021-05-12 13:49 UTC, umapraseeda approved these changes

2021-05-14 05:14 UTC, peknis approved these changes

2021-05-25 07:45 UTC, merged