doc: Azure doc fixes
NordicSemiconductor/asset-tracker-cloud-docs pull request #174
Opened 2021-05-28 15:39 UTC by umapraseeda

Azure doc fixes

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

2021-05-31 08:06 UTC, coderbyheart requested changes
- `Azure Function App`/`Azure Function` is a product name, capitalize in all instances
- use guilabel for all GUI elements

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. Enter the B2C Open ID Connect metadata URL into the :guilabel:`Issuer URI` field and click ``OK`` to finish the configuration.
```suggestion
#. Enter the B2C OpenID Connect metadata URL into the :guilabel:`Issuer URI` field and click :guilabel:`OK` to finish the configuration.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. Select the entry that corresponds to your Azure function app in the :guilabel:`Application` field.
```suggestion
   #. Select the entry that corresponds to your Azure Function App in the :guilabel:`Application` field.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. After the users complete these flows, they are redirected to the Azure function app.
```suggestion
   #. After the users complete these flows, they are redirected to the Azure Function App.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +To secure access to your Azure function apps and to allow access only to authenticated users, you can use Azure Active Directory B2C.
```suggestion
To secure access to your Azure Function App and to allow access only to authenticated users, you can use Azure Active Directory B2C.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. Click :guilabel:`+Create a Resource` to create your Azure function app.
```suggestion
#. Click :guilabel:`+Create a Resource` to create your Azure Function App.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +	  * In the :guilabel:`Reply URL` field, enter the unique Azure function app name that you created in step 4 and append  ``/.auth/login/aad/callback`` to it. For example, ``https://myAppSecuredByB2C.
```suggestion
	  * In the :guilabel:`Reply URL` field, enter the unique Azure Function App name that you created in step 4 and append  ``/.auth/login/aad/callback`` to it. For example, ``https://myAppSecuredByB2C.azurewebites.net/.auth/login/aad/callback``.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. Enter a unique name for your function app, fill the remaining information and click :guilabel:`Create`.
```suggestion
#. Enter a unique name for your Function App, fill the remaining information and click :guilabel:`Create`.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   Once the function app is created, click :guilabel:`Go to resource` to view the created function app.
```suggestion
   Once the Function App is created, click :guilabel:`Go to resource` to view the created Function App.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +	  The default action when a request is not authenticated is ``Allow Anonymous request``. This allows any user to access your function app.
```suggestion
	  The default action when a request is not authenticated is ``Allow Anonymous request``. This allows any user to access your Function App.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   a. Click the function app that you created.
```suggestion
   a. Click the Function App that you created.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +1. Confirm that users without authentication gets prompted to complete their B2C sign-in before being allowed access to your function app:
```suggestion
1. Confirm that users without authentication gets prompted to complete their B2C sign-in before being allowed access to your Function App:
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. After a successful access to the function app, open a separate browser tab and validate that you can automatically sign in.
```suggestion
   #. After a successful access to the Function App, open a separate browser tab and validate that you can automatically sign in.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. Select ``Log in with Azure Active Directory`` in the :guilabel:`Action to take when request is not authenticated` field.
```suggestion
#. Select :guilabel:`Log in with Azure Active Directory` in the :guilabel:`Action to take when request is not authenticated` field.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. In the ``Function App`` blade, click :guilabel:`Create`.
```suggestion
   #. In the :guilabel:`Function App` blade, click :guilabel:`Create`. 
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. In the :guilabel:`Authentication/Authorization` blade, move the sliding button under :guilabel:`App Service Authentication` to ``On``. Several authentication provider configurations are now displa
```suggestion
#. In the :guilabel:`Authentication/Authorization` blade, move the sliding button under :guilabel:`App Service Authentication` to :guilabel:`On`. Several authentication provider configurations are now displayed.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +#. Select ``Azure Active Directory`` under the :guilabel:`Authentication Providers` list.
```suggestion
#. Select :guilabel:`Azure Active Directory` under the :guilabel:`Authentication Providers` list.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +	  * Select ``Yes`` for the :guilabel:`Web App/ Web API` option.
```suggestion
	  * Select :guilabel:`Yes` for the :guilabel:`Web App/ Web API` option.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> -Manual Guide by `Saurabh Sharma <https://docs.microsoft.com/answers/answers/40449/view.html>`_.
Original author removed.

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   Use this ID to complete the Azure function configuration.
```suggestion
   Use this ID to complete the Azure Function configuration.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   a. Clear the browser session cookies and confirm that the user needs to authenticate during an attempt to access your Azure function.
```suggestion
   a. Clear the browser session cookies and confirm that the user needs to authenticate during an attempt to access your Azure Function.
```

2021-05-31 08:06 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. Run other user flows, such as password reset or profile edit, with your Azure function.
```suggestion
   #. Run other user flows, such as password reset or profile edit, with your Azure Function.
```

2021-05-31 11:44 UTC, peknis requested changes

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +      :alt: 1
Do we want to have a caption for the image?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. Obtain the Application ID from the Properties blade of the application.
```suggestion
   #. Obtain the Application ID from the :guilabel:`Properties` blade of the application.
```

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. Select :guilabel:`Applications`, then select :guilabel:`+Add`.
```suggestion
   #. Select :guilabel:`Applications` > :guilabel:`+Add`.
```

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +      :alt: 10
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
Caption?

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +To configure Azure AD B2C as the identity provider for your function apps, complete the following steps:
Another instance of "function apps".

2021-05-31 11:44 UTC, peknis commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +Users can access the function apps only after a successful authentication.
Do we need to capitalize also this instance of "function apps"?

2021-06-11 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NordicSemiconductor/asset-tracker-cloud-docs?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NordicSemiconductor/asset-tracker-cloud-docs?pullRequest=174) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: umapraseeda<br/>:x: wiba-nordic<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicSemiconductor/asset-tracker-cloud-docs?pullRequest=174) it.</sub>

2021-06-11 12:07 UTC, wiba-nordic commented
I took out the illustrations, because when I was following the instructions, they weren't really helping and they were out of date with the updated Azure UI.

2021-06-11 12:13 UTC, peknis commented
The doc has now been stripped off all images. A few images might help the reader to navigate, and at least gives a bit of breath in a long procedure like this.

2021-06-11 12:29 UTC, peknis commented
> * `Azure Function App`/`Azure Function` is a product name, capitalize in all instances
> * use guilabel for all GUI elements

One could argue whether or not Function App needs to be capitalized or not. See for example MS's own docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal

2021-06-17 10:36 UTC, coderbyheart approved these changes

2021-06-17 10:36 UTC, coderbyheart commented on docs/azure/secure-azure-function-apps-with-microsoft-b2c.rst
> +   #. Under ``Function App``, click :guilabel:`Create`.
```suggestion
   #. Under :guilabel:`Function App`, click :guilabel:`Create`.
```

2021-06-17 11:22 UTC, peknis approved these changes

2021-06-17 11:27 UTC, merged