fix(azure): storage accounts have changed
NordicSemiconductor/asset-tracker-cloud-docs pull request #311
Opened 2021-11-04 14:03 UTC by coderbyheart

2021-11-04 14:12 UTC, peknis requested changes

2021-11-04 14:12 UTC, peknis commented on docs/azure/GettingStarted/Deploy.rst
> +   Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
```suggestion
   Storage account names must be between 3 and 24 characters and may contain numbers and lowercase letters only.
```

2021-11-05 06:09 UTC, wiba-nordic approved these changes

2021-11-05 07:44 UTC, umapraseeda approved these changes

2021-11-05 08:23 UTC, merged