feat: rename GPS to GNSS
NordicSemiconductor/asset-tracker-cloud-docs pull request #352
Opened 2021-12-10 12:57 UTC by coderbyheart

nRF9160 supports mutliple satelite position systems, so use the
more generic term Global Navigation Satellite System (GNSS).

Fixes #351

BREAKING CHANGE: this renames the configuration and data property

2021-12-10 13:08 UTC, peknis requested changes

2021-12-10 13:08 UTC, peknis commented on docs/aws/desired-cfg.json
> +    "gnst": 720,
gnsst?

2021-12-10 13:41 UTC, coderbyheart commented on docs/aws/desired-cfg.json
> +    "gnst": 720,
```suggestion
    "gnsst": 720,
```

2021-12-13 06:14 UTC, wiba-nordic approved these changes

2021-12-13 06:43 UTC, peknis approved these changes

2021-12-20 09:56 UTC, simensrostad requested changes

2021-12-20 09:56 UTC, simensrostad commented on docs/devices/TroubleShooting.rst
> +Error: GNSS_EVT_OPERATION_BLOCKED
```suggestion
Error: NRF_MODEM_GNSS_EVT_BLOCKED
```

2021-12-20 09:56 UTC, simensrostad commented on docs/devices/TroubleShooting.rst
> +Error: GNSS_EVT_OPERATION_BLOCKED
This event name changed when the GPS module was updated to use the GNSS API in
https://github.com/simensrostad/fw-nrfconnect-nrf/commit/e8488c9d4eb98d7fb877a00bb5043792ea66ed84

2022-01-10 08:49 UTC, peknis approved these changes

2022-01-10 10:22 UTC, merged