fix(aws): document nRF Cloud team ID
NordicSemiconductor/asset-tracker-cloud-docs pull request #391
Opened 2022-02-09 13:00 UTC by coderbyheart

The team ID has to be set in order to be able
to use any Location Service.

2022-02-09 13:10 UTC, peknis requested changes

2022-02-09 13:10 UTC, peknis commented on docs/aws/nRFCloudLocationServices.rst
> +Any nRF Cloud Location Service requires the configuration of your team ID.
```suggestion
To use any nRF Cloud Location Service, you need to configure your team ID.
```

2022-02-09 13:10 UTC, peknis commented on docs/aws/nRFCloudLocationServices.rst
> +Use the following command to configure your team ID:
```suggestion
Run the following command to configure your team ID:
```

2022-02-09 13:35 UTC, wiba-nordic approved these changes
Looks good as long as Pekka's requested changes are handled.

2022-02-10 06:22 UTC, peknis approved these changes

2022-02-10 08:31 UTC, merged