fix: use nrf-docker image
NordicSemiconductor/asset-tracker-cloud-docs pull request #476
Opened 2022-06-10 12:53 UTC by MLopezJ

The intermediate docker image is no longer needed.

2022-06-10 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/NordicSemiconductor/asset-tracker-cloud-docs?pullRequest=476) <br/>All committers have signed the CLA.

2022-06-10 14:08 UTC, coderbyheart approved these changes

2022-06-10 14:52 UTC, coderbyheart commented
@MLopezJ please sign the CLA.

2022-06-10 15:01 UTC, MLopezJ commented
@coderbyheart Just signed the CLA. Thanks for the catch up

2022-06-13 05:48 UTC, wiba-nordic approved these changes

2022-06-13 05:52 UTC, peknis approved these changes

2022-06-13 06:27 UTC, coderbyheart commented
@Lenakh97 please verify fix

2022-06-13 07:05 UTC, umapraseeda approved these changes

2022-06-13 11:43 UTC, wiba-nordic requested changes

2022-06-13 11:43 UTC, wiba-nordic commented on docs/firmware/aws/BuildingUsingDocker.rst
> +To clone firmware repository, run the following commands:
```suggestion
To clone the firmware repository, run the following commands:
```

2022-06-13 11:43 UTC, wiba-nordic commented on docs/firmware/azure/BuildingUsingDocker.rst
> +To clone firmware repository, run the following commands:
```suggestion
To clone the firmware repository, run the following commands:
```

2022-06-13 12:02 UTC, wiba-nordic approved these changes

2022-06-13 12:41 UTC, coderbyheart commented
@MLopezJ @Lenakh97 I've updated the instruction an can build it on my system. Please verify.

Don't forget to pull the latest image version:

   docker pull nordicplayground/nrfconnect-sdk:main

2022-06-14 07:19 UTC, MLopezJ commented
New implementation verified and now the behavior is the expected. 

Just adding an small improvement in the documentation with the intention of decrease confusion for documentation readers.

2022-06-14 09:21 UTC, coderbyheart commented
Extracted unrelated changes to #478

2022-06-14 09:22 UTC, merged