feat(cfg): extend accelerometer config
NordicSemiconductor/asset-tracker-cloud-docs pull request #498
Opened 2022-07-05 08:44 UTC by maxd-nordic

This patch extends the existing accelerometer configuration options.
Its device-side pendant can be found in https://github.com/nrfconnect/sdk-nrf/pull/8020.

BREAKING CHANGE: the "acct" config property has been renamed to "accath",
and the properties "accith" and "accito" are introduced.

Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>

2022-07-07 14:44 UTC, coderbyheart requested changes

2022-07-07 14:44 UTC, coderbyheart commented on docs/cloud-protocol/cfg.schema.json
> +      "description": "Accelerometer inactivity timeout in ms: Hystersis timeout for stillness detection.",
```suggestion
      "description": "Accelerometer inactivity timeout in ms: Hysteresis timeout for stillness detection.",
```

2022-07-07 15:34 UTC, maxd-nordic commented on docs/cloud-protocol/cfg.schema.json
> +      "description": "Accelerometer inactivity timeout in ms: Hystersis timeout for stillness detection.",
done

2022-08-01 09:33 UTC, coderbyheart approved these changes

2022-08-22 14:23 UTC, closed without merging